Portfolio: Website content
lily4178993/Portfolio pull request #1
Opened 2023-04-27 20:55 UTC by lily4178993

<h1> Microverse module 1: Week 1</h1>
<h2>Portfolio Project (Mobile version)</h2>

In this branch, I have:

- added a [HTML ](https://github.com/lily4178993/Portfolio/blob/website-content/index.html) and [CSS](https://github.com/lily4178993/Portfolio/blob/website-content/styles.css) files
- added a [gitignore file](https://github.com/lily4178993/Portfolio/blob/website-content/.gitignore)
- added a [README file](https://github.com/lily4178993/Portfolio/blob/website-content/README.md)
- Set up linters for HTML and CSS
- create a [design folder](https://github.com/lily4178993/Portfolio/tree/website-content/design) that contains the screenshots of the mobile version
- create a [styles guideline](https://github.com/lily4178993/Portfolio/blob/website-content/style-guide.md)

2023-04-27 21:48 UTC, tugsem requested changes
##  STATUS: REQUIRED CHANGES ♻️
Hello @lily4178993 👋 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
✔️linters are passing
✔️correct use of github flow
✔️professional commits and pr description
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 21:48 UTC, tugsem commented on README.md
> +
- [ ]  Please fill these areas with the information users need to install and run this project locally. If you feel there is nothing to write under a header, kindly remove them.

2023-04-27 21:48 UTC, tugsem commented on index.html
> +        <div class="logo"><p>My Logo</p></div>
- [ ] Kindly wrap your logo inside an `a` tag. This would be semantically correct.

2023-04-27 21:48 UTC, tugsem commented on index.html
> +            <p>I'm a Software Developer</p>
- [ ] This is an example of a subheader. Kindly use `h2` tag to make it semantically correct.

2023-04-27 21:48 UTC, tugsem commented on index.html
> +                <li><img src="images/medium.png" alt="twitter icon"></li>
- [ ] Each image in the list item should be wrapped inside an `a` tag. Apart from being semantically correct, the a tag will let you connect your social networks with the icons, using href.

2023-04-27 23:50 UTC, lily4178993 commented
Tank you @tugsem for taking your time to review my code 😄 !

2023-04-28 00:19 UTC, MaganaAsiati approved these changes
# Status: Approved [✔️](https://emojipedia.org/check-mark/)
## Hi @lily4178993   , I'm @MaganaAsiati , your reviewer for this PR  :wave: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


![clap](https://media0.giphy.com/media/j2GPljpvL8Lulm3d0X/giphy.gif)

## Highlights
- descriptive README file  :heavy_check_mark:👨🏻‍💻
- Your commits should start with a capital letter :heavy_check_mark:👨🏻‍💻


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future.
- [ ] kindly  Add a descriptive description in your pull request in future which give more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Cheers and Happy coding!👏👏👏

2023-04-28 00:26 UTC, lily4178993 commented
Tank you @MaganaAsiati for taking your time to review my code 😄 !

2023-04-28 00:28 UTC, merged